/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;
import Maq_Bebidas.Bebidas;
import Maq_Monedas.Monedas;
import VentanasBebida.VentanaCC;
import VentanasBebida.VentanaFanta;
import VentanasBebida.VentanaPepsi;
import VentanasBebida.VentanaSprite;
import java.awt.Color;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionAdapter;
import java.awt.event.MouseMotionListener;
import static java.lang.Thread.sleep;
import java.net.URL;
import java.util.ArrayList;
import java.util.Collections;
import static java.util.Collections.list;
import java.util.HashSet;
import java.util.Set;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.TransferHandler;

/**
 *
 * @author JoeL
 */
public class Ventana_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Principal
     */
    
    static public Publicidad hilo;
    int acum;
    double valor;
    int opBebidad=0;
    static int indiceM;
    static int indiceB;
    int cant5;
    int cant10;
    int cant25;
    int bandera=0;
    int cont=0;
    boolean sw=true,sw2=true;
    public static ArrayList<String> monedas = new ArrayList<String>();
    public Ventana_Principal() {
        //monedaCinco.setToolTipText("<html><img src=\"" + Ventana_Principal.class.getResource("Multimedia/cinco_1.png")+ "\"> Tooltip ");
        initComponents();
        this.setTitle("Maquina Expendedora de Bebidas");
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Multimedia/dasd.png"));
        setIconImage(icon);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        jScrollPane1.setBorder(null);
        panelMain.setBackground(Color.WHITE);
        insertImage(panelMain,"/Multimedia/fondo.png",616,467);
        insertImage(panelPant,"/Multimedia/pant.png",340,100);
        //-------------------------------------------------------
        
        Procesos_Maq proc=new Procesos_Maq(opBebidad, cant5, cant10, cant25, valor, acum, monedas);
        proc.q0();
        hilo=proc.hilo;
        //-------------------------------------------------------
        dragText();
        handCursor();
        btnCocacola.requestFocus();
        txtMon.setText(0+"");
        arrow.setVisible(false);
        arrow2.setVisible(false);
        opBebidad=0;
        //lblPush.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        btnCocacola = new javax.swing.JButton();
        btnSprite = new javax.swing.JButton();
        btnFanta = new javax.swing.JButton();
        btnPepsi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        panelPant = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtA = new javax.swing.JTextArea();
        monedaCinco = new javax.swing.JLabel();
        monedad = new javax.swing.JLabel();
        txtMon = new javax.swing.JTextField();
        monedavc = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        arrow = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl25 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        lbl10 = new javax.swing.JLabel();
        lblCambio = new javax.swing.JButton();
        arrow2 = new javax.swing.JLabel();
        lblCanc = new javax.swing.JLabel();
        lblPush = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblcong = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        btnCocacola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/l2.png"))); // NOI18N
        btnCocacola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCocacolaActionPerformed(evt);
            }
        });

        btnSprite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/l3.png"))); // NOI18N
        btnSprite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSpriteActionPerformed(evt);
            }
        });

        btnFanta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/l4.jpg"))); // NOI18N
        btnFanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFantaActionPerformed(evt);
            }
        });

        btnPepsi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/l6.jpg"))); // NOI18N
        btnPepsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPepsiActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setText("¡Escoje tu Bebida Favorita!");

        panelPant.setBackground(new java.awt.Color(255, 255, 255));

        txtA.setColumns(20);
        txtA.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        txtA.setRows(5);
        txtA.setBorder(null);
        txtA.setCaretColor(new java.awt.Color(255, 255, 255));
        txtA.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(txtA);

        javax.swing.GroupLayout panelPantLayout = new javax.swing.GroupLayout(panelPant);
        panelPant.setLayout(panelPantLayout);
        panelPantLayout.setHorizontalGroup(
            panelPantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPantLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        panelPantLayout.setVerticalGroup(
            panelPantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPantLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        monedaCinco.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        monedaCinco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/cinco_1.png"))); // NOI18N
        monedaCinco.setText("5");
        monedaCinco.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        monedaCinco.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        monedaCinco.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        monedaCinco.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        monedaCinco.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                monedaCincoMouseDragged(evt);
            }
        });
        monedaCinco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                monedaCincoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                monedaCincoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                monedaCincoMouseReleased(evt);
            }
        });

        monedad.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        monedad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/diez.png"))); // NOI18N
        monedad.setText("10");
        monedad.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        monedad.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        monedad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                monedadMouseClicked(evt);
            }
        });

        txtMon.setForeground(new java.awt.Color(255, 255, 255));
        txtMon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        txtMon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtMonMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtMonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtMonMouseReleased(evt);
            }
        });
        txtMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMonActionPerformed(evt);
            }
        });

        monedavc.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        monedavc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/vcinco.png"))); // NOI18N
        monedavc.setText("25");
        monedavc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        monedavc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        monedavc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                monedavcMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        jLabel2.setText("Ingresar Monedas:");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/coin_1.png"))); // NOI18N

        arrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/arrow_(2).gif"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        jLabel4.setText("Cambio: ");

        lbl25.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        lbl25.setText("0");

        lbl5.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        lbl5.setText("0");

        lbl10.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        lbl10.setText("0");

        lblCambio.setBackground(new java.awt.Color(255, 255, 255));
        lblCambio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/ret_1.png"))); // NOI18N
        lblCambio.setBorder(null);
        lblCambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblCambioActionPerformed(evt);
            }
        });

        arrow2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/arrow_(2).gif"))); // NOI18N

        lblCanc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/canc_1.png"))); // NOI18N
        lblCanc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCancMouseClicked(evt);
            }
        });

        lblPush.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/pullpush.png"))); // NOI18N
        lblPush.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPushMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        jLabel5.setText("1.00");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        jLabel7.setText("0.85");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        jLabel8.setText("0.75");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        jLabel9.setText("0.50");

        lblcong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/conf_1.png"))); // NOI18N
        lblcong.setText("             ");
        lblcong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblcongMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addComponent(lblcong, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109)
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelMainLayout.createSequentialGroup()
                                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(panelPant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelMainLayout.createSequentialGroup()
                                        .addGap(73, 73, 73)
                                        .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelMainLayout.createSequentialGroup()
                                                .addComponent(monedavc)
                                                .addGap(18, 18, 18)
                                                .addComponent(monedaCinco)
                                                .addGap(18, 18, 18)
                                                .addComponent(monedad))
                                            .addGroup(panelMainLayout.createSequentialGroup()
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtMon, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(panelMainLayout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel2)))))
                        .addContainerGap())
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelMainLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelMainLayout.createSequentialGroup()
                                        .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnCocacola, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnFanta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnPepsi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnSprite, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(panelMainLayout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(jLabel5)
                                        .addGap(94, 94, 94)
                                        .addComponent(jLabel7))
                                    .addGroup(panelMainLayout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelMainLayout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(lblPush, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(panelMainLayout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(94, 94, 94)
                                                .addComponent(jLabel9)))))
                                .addGap(80, 80, 80)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18))
                            .addGroup(panelMainLayout.createSequentialGroup()
                                .addGap(256, 256, 256)
                                .addComponent(arrow)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelMainLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblCanc, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(panelMainLayout.createSequentialGroup()
                                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panelMainLayout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(lbl25)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbl5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblCambio))
                                .addGap(18, 18, 18)
                                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(arrow2, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMainLayout.createSequentialGroup()
                                        .addComponent(lbl10, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(43, 43, 43))))))))
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(panelPant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtMon)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelMainLayout.createSequentialGroup()
                                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnCocacola, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSprite, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnFanta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPepsi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)))
                            .addGroup(panelMainLayout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPush, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                            .addComponent(arrow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(monedaCinco)
                            .addComponent(monedad)
                            .addComponent(monedavc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lbl25)
                            .addComponent(lbl5)
                            .addComponent(lbl10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCambio)
                            .addComponent(arrow2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addComponent(lblCanc, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMainLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblcong))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCocacolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCocacolaActionPerformed
        cont=1;        
        if(sw && cont>=1)
        {
                Procesos_Maq proc=new Procesos_Maq(opBebidad, cant5, cant10, cant25, valor, acum, monedas);

                opBebidad=1;
                txtA.setText("");
                valor=format(proc.valorBeb(1));
                ScheduledExecutorService timer = Executors.newSingleThreadScheduledExecutor();
                timer.scheduleAtFixedRate(hilo, 1, 1, TimeUnit.MINUTES);
        }else{
            JOptionPane.showMessageDialog(null,"No se puede seleccionar otra bebida, despues de haber ingresado un valor");
        
        }
            
    }//GEN-LAST:event_btnCocacolaActionPerformed

    private void btnSpriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpriteActionPerformed
        cont=1;
        if(sw && cont>=1)
        {
            Procesos_Maq proc=new Procesos_Maq(opBebidad, cant5, cant10, cant25, valor, acum, monedas);
            
            opBebidad=2;
            txtA.setText("");
            valor=format(proc.valorBeb(2));
            ScheduledExecutorService timer = Executors.newSingleThreadScheduledExecutor();
            timer.scheduleAtFixedRate(hilo, 1, 1, TimeUnit.MINUTES);        
        }else{
            JOptionPane.showMessageDialog(null,"No se puede seleccionar otra bebida, despues de haber ingresado un valor");
        
        }
    }//GEN-LAST:event_btnSpriteActionPerformed

    private void btnFantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFantaActionPerformed
         cont=1;
        if(sw && cont>=1)
        {
        Procesos_Maq proc=new Procesos_Maq(opBebidad, cant5, cant10, cant25, valor, acum, monedas);
        //hilo.stop();
        opBebidad=3;
        txtA.setText("");
        valor=format(proc.valorBeb(3));
        ScheduledExecutorService timer = Executors.newSingleThreadScheduledExecutor();
            timer.scheduleAtFixedRate(hilo, 1, 1, TimeUnit.MINUTES);
             }else{
            JOptionPane.showMessageDialog(null,"No se puede seleccionar otra bebida, despues de haber ingresado un valor");
        
        }
    }//GEN-LAST:event_btnFantaActionPerformed

    private void btnPepsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPepsiActionPerformed
        cont=1;
        if(sw && cont>=1)
        {
        Procesos_Maq proc=new Procesos_Maq(opBebidad, cant5, cant10, cant25, valor, acum, monedas);
        //hilo.stop();
        opBebidad=4;
        txtA.setText("");
        valor=format(proc.valorBeb(4));
        ScheduledExecutorService timer = Executors.newSingleThreadScheduledExecutor();
            timer.scheduleAtFixedRate(hilo, 1, 1, TimeUnit.MINUTES);
        }else{
            JOptionPane.showMessageDialog(null,"No se puede seleccionar otra bebida, despues de haber ingresado un valor");
        
        }
    }//GEN-LAST:event_btnPepsiActionPerformed

    private void txtMonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMonMouseClicked
        
        
    }//GEN-LAST:event_txtMonMouseClicked

    private void txtMonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMonMouseReleased

    }//GEN-LAST:event_txtMonMouseReleased

    private void txtMonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMonMousePressed
        
    }//GEN-LAST:event_txtMonMousePressed

    private void txtMonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMonMouseEntered

        sw2=false;    
        if(opBebidad!=0)
        {
            
            sw=false;
            
            cont++;
            int acum2=0,cont=0;
            acum2=acum;
            acum+=Integer.parseInt(txtMon.getText().trim());
            sw2=true;    
            
            cont=acum-acum2;
            Procesos_Maq proc=new Procesos_Maq(opBebidad, cant5, cant10, cant25, valor, acum, monedas);
            proc.q1(0,2,cont);
            controlLista();
        }else
        {
            JOptionPane.showMessageDialog(null,"No se ha seleccionado una bebida...");
            txtMon.setText("");
        }
        
        
    }//GEN-LAST:event_txtMonMouseEntered

    private void lblCancMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancMouseClicked

        if(opBebidad!=0 && acum>0)
        {
            if(sw2)
            {
                  Procesos_Maq proc=new Procesos_Maq(opBebidad, cant5, cant10, cant25, valor, acum, monedas);
                bandera=1;
                arrow2.setVisible(true);
                proc.q1(0,1,0);
                arrow.setVisible(false);
                cant10=0;
                cant5=0;
                cant25=0;
            }
          
            
        }
        else
        {
            JOptionPane.showMessageDialog(null,"No se puede realizar esta acción...");
        }
    }//GEN-LAST:event_lblCancMouseClicked

    private void lblCambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblCambioActionPerformed
        sw=false;
        
        if(opBebidad!=0 && acum>0 && arrow2.isVisible())
        {
            
        
        if(bandera!=1 && arrow2.isVisible())
        {
            arrow2.setIcon(new ImageIcon(getClass().getResource("/Multimedia/ok.gif")));
            sw2=false;
            lbl5.setText("0");
            lbl10.setText("0");
            lbl25.setText("0");
            //lblCambio.setEnabled(false);
        }else
        {
            this.dispose();
            JOptionPane.showMessageDialog(null,"Vuelva Pronto...");
            Ventana_Principal obj=new Ventana_Principal();
            obj.setVisible(true);
            txtA.setText("");
            arrow2.setVisible(false);
            acum=0;
            valor=0;
            opBebidad=0;
            monedas.clear();
            cant5=0;
            cant10=0;
            cant25=0;
        }
        }else
        {
        
            JOptionPane.showMessageDialog(null,"No se puede realizar esta acción...");
        }
        
        
    }//GEN-LAST:event_lblCambioActionPerformed

    private void lblPushMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPushMouseClicked
        if(arrow2.isVisible() && !(lbl5.getText().equals("0") && lbl10.getText().equals("0") && lbl25.getText().equals("0")))
        {
            JOptionPane.showMessageDialog(null,"No olvide retirar su cambio...");
        }else{
            Procesos_Maq proc=new Procesos_Maq(opBebidad, cant5, cant10, cant25, valor, acum, monedas);
            if(opBebidad!=0 && acum>0 && arrow.isVisible()){




            proc.aumentarStockMon();
            if(opBebidad==1)
            {
                lblPush.setIcon(new ImageIcon(getClass().getResource("/Multimedia/l21.png")));
            }else
            if(opBebidad==2)
            {
                lblPush.setIcon(new ImageIcon(getClass().getResource("/Multimedia/l3_1.png")));
            }else
            if(opBebidad==3)
            {
                lblPush.setIcon(new ImageIcon(getClass().getResource("/Multimedia/l4_1.jpg")));
            }else
            if(opBebidad==4)
            {
                lblPush.setIcon(new ImageIcon(getClass().getResource("/Multimedia/l6_1.jpg")));
            }

            arrow.setIcon(new ImageIcon(getClass().getResource("/Multimedia/ok.gif")));
            proc.q2(0);
            acum=0;
            valor=0;
            opBebidad=0;
            monedas.clear();
            cant5=0;
            cant10=0;
            cant25=0;
            this.dispose();
        }else
        {
            JOptionPane.showMessageDialog(null,"No se puede realizar esta acción...");
        }
    }
        
    }//GEN-LAST:event_lblPushMouseClicked

    private void txtMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMonActionPerformed

    private void lblcongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcongMouseClicked
        ControlMaquina obj=new ControlMaquina();
        obj.setVisible(true);
    }//GEN-LAST:event_lblcongMouseClicked

    private void monedaCincoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monedaCincoMouseDragged
                
    }//GEN-LAST:event_monedaCincoMouseDragged

    private void monedaCincoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monedaCincoMousePressed

    }//GEN-LAST:event_monedaCincoMousePressed

    private void monedaCincoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monedaCincoMouseReleased
        
    }//GEN-LAST:event_monedaCincoMouseReleased

    private void monedavcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monedavcMouseClicked

        if(opBebidad==0)
        {
            txtMon.setEnabled(false);
            JOptionPane.showConfirmDialog(null,"No se ha seleccionado una bebida...");
        }else
        {
            txtMon.setEnabled(true);
        }
    }//GEN-LAST:event_monedavcMouseClicked

    private void monedaCincoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monedaCincoMouseClicked
        if(opBebidad==0)
        {
            txtMon.setEnabled(false);
            JOptionPane.showConfirmDialog(null,"No se ha seleccionado una bebida...");
        }else
        {
            txtMon.setEnabled(true);
        }
    }//GEN-LAST:event_monedaCincoMouseClicked

    private void monedadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monedadMouseClicked
    if(opBebidad==0)
        {
            txtMon.setEnabled(false);
            JOptionPane.showMessageDialog(null,"No se puede realizar esta acción...");
        }else
        {
            txtMon.setEnabled(true);
        }
    }//GEN-LAST:event_monedadMouseClicked

    
    
    
   
    //****************************************************************************************************
    public void dragText()
    {
        monedaCinco.setTransferHandler(new TransferHandler("text"));
        monedad.setTransferHandler(new TransferHandler("text"));
        monedavc.setTransferHandler(new TransferHandler("text"));
        
        MouseListener listener = new MouseAdapter() {
        public void mousePressed(MouseEvent me) {
            JComponent comp = (JComponent) me.getSource();
            TransferHandler handler = comp.getTransferHandler();
            handler.exportAsDrag(comp, me, TransferHandler.COPY);
        }
    };
    
    monedaCinco.addMouseListener(listener);
    monedad.addMouseListener(listener);
    monedavc.addMouseListener(listener);
    }

    public int format (double valor)
    {
        String value="";
        if(valor>=1)
        {
            String x=Double.toString(valor);
            value=x.replace(".","");
            if(value.length()<=2)
            {
                value=value.concat("0");
            }
            
        }else
        {
            String x=Double.toString(valor);
            int aux=x.indexOf(".");
            value=x.substring(aux+1);
        
            if(x.length()<4)
            {
                value=value.concat("0");
            }
            
        }
        
    return Integer.parseInt(value);
    }
    public void controlLista()//Remueve los 0 de la lista monedas
    {
        for (int i = 0; i < monedas.size(); i++) 
        {
            if(monedas.get(i).equals("0"))
            {
                monedas.remove(i);
            }   
        }
      
    }
   
    public void insertImage(JPanel panel,String ruta,int x, int y)
    {
        ImagePanel Imagen = new ImagePanel(ruta,x,y);
        panel.add(Imagen);
        panel.repaint();
    }
    public class ImagePanel extends JPanel 
    {
        private final String ruta;
        private final int x;
        private final int y;
        public ImagePanel(String ruta,int x,int y)
        {
            //Se crea un método cuyo parámetro debe ser un objeto Graphics
            this.ruta=ruta;
            this.x=x;
            this.y=y;
            this.setSize(x,y);
        } 
        @Override
        public void paint(Graphics grafico)
        {
            Dimension height = getSize();
            //Se selecciona la imagen que tenemos en el paquete de la //ruta del programa
            ImageIcon Img = new ImageIcon(getClass().getResource(ruta)); 
            //se dibuja la imagen que tenemos en el paquete Images //dentro de un panel
            grafico.drawImage(Img.getImage(), 0, 0, height.width, height.height, null);
            setOpaque(false);
            super.paintComponent(grafico);
        }
    }
    public void handCursor()
    {
        monedaCinco.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));  
        monedavc.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));  
        monedad.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));  
        lblPush.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));  
        lblCambio.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));  
        lblCanc.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));  
        lblcong.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));  
        btnCocacola.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));  
        btnFanta.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));  
        btnPepsi.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));  
        btnSprite.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));  
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel arrow;
    public static javax.swing.JLabel arrow2;
    private javax.swing.JButton btnCocacola;
    private javax.swing.JButton btnFanta;
    private javax.swing.JButton btnPepsi;
    private javax.swing.JButton btnSprite;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JLabel lbl10;
    public static javax.swing.JLabel lbl25;
    public static javax.swing.JLabel lbl5;
    private javax.swing.JButton lblCambio;
    private javax.swing.JLabel lblCanc;
    public static javax.swing.JLabel lblPush;
    private javax.swing.JLabel lblcong;
    public static javax.swing.JLabel monedaCinco;
    public static javax.swing.JLabel monedad;
    public static javax.swing.JLabel monedavc;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelPant;
    public static javax.swing.JTextArea txtA;
    public static javax.swing.JTextField txtMon;
    // End of variables declaration//GEN-END:variables

}


